In [1]:
import tensorflow as tf

In [5]:
x = tf.constant(3)
print(x)
print(type(x))
print(x.shape)

tf.Tensor(3, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
()


In [6]:
x = tf.constant([3,5,7])
print(x)
print(type(x))
print(x.shape)

tf.Tensor([3 5 7], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(3,)


In [7]:
x = tf.constant([[3,5,7],[4,6,8]])
print(x)
print(type(x))
print(x.shape)

tf.Tensor(
[[3 5 7]
 [4 6 8]], shape=(2, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 3)


In [8]:
x = tf.constant([[[3,5,7],[4,6,8]], [[3,5,7],[4,6,8]]])
print(x)
print(type(x))
print(x.shape)

tf.Tensor(
[[[3 5 7]
  [4 6 8]]

 [[3 5 7]
  [4 6 8]]], shape=(2, 2, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 2, 3)


Stack

In [14]:
x1 = tf.constant([3,5,7])
x2 = tf.stack([x1, x1])
print(x2.shape)
x3 = tf.stack([x2, x2, x2, x2])
print(x3.shape)
x4 = tf.stack([x3, x3])
print(x4.shape)

(2, 3)
(4, 2, 3)
(2, 4, 2, 3)


 - tf.constant() creates constants
 - tf.Variable() creates variables

Reshape

In [17]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])

print(x[:,1])

y = tf.reshape(x, [3,2])
print(x)
print(y)

tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [20]:
x = tf.Variable(2.0, dtype = tf.float32, name = 'my_variable')
print(x)
x.assign(3.0)
print(x)
x.assign_add(2.0)
print(x)
x.assign_sub(1.0)
print(x)

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=2.0>
<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=3.0>
<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=5.0>
<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=4.0>


- Tensorflow can calculate the derivative of any function with respect to any parameter
- The computations are recorded in GradientTape

In [24]:
tf.Tensor

tensorflow.python.framework.tensor.Tensor